image: java:8

stages:
  - build

  
before_script:
  - echo installing maven...
  - apt-get update -y
  - apt-get install -y maven
  
build:
  stage: build
  script: mvn clean install
  artifacts:
    paths:
      - target/*.war


